apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "perfx.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perfx.labels" . | nindent 4 }}
    {{- with .Values.frontend.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.frontend.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "perfx.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "perfx.labels" . | nindent 8 }}
        {{- include "perfx.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "perfx.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "perfx.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perfx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "perfx.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
