{{- if and .Values.ingress.enabled (not .Values.route.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "perfx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perfx.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "perfx.fullname" . }}-backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "perfx.fullname" . }}-frontend
                port:
                  name: http
{{- end }}
