{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perfx.fullname" . }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perfx.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB:       {{ include "perfx.databaseName" . | quote }}
  POSTGRES_USER:     {{ include "perfx.databaseUser" . | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
{{- end }}
